version: '3'
services:
  db:
    image: mongo
    ports:
      - "27017:27017"
    command: mongod --smallfiles --logpath=/dev/null # --quiet
    volumes:
      - db-data:/data/db mongo
      - mongo-config:/data/configdb
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
volumes:
  db-data:
  mongo-config:
