version: '3'
services:
  db:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - db-data:/data/db mongo
      - mongo-config:/data/configdb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
volumes:
  db-data:
  mongo-config:
